spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MHarris021/cloudbees-todo-app.git
          search-paths: configurations
management:
  endpoint:
    shutdown:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'