management:
  endpoint:
    shutdown:
      enabled: false
    refresh:
      enabled: true
    restart:
      enabled: true
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registry-fetch-interval-seconds: 30
