spring:
  application:
    name: todo-gateway-service
server:
  port: 8080
zuul:
  ignored-headers:
    - Access-Control-Allow-Credentials
    - Access-Control-Allow-Origin
  routes:
    todo-rest-service:
      path: /todo-rest-service/**
      sensitive-headers:
      - Set-Cookie
      - Authorization
    todo-discovery-service:
      path: /todo-discovery-service/**
      sensitive-headers:
      - Set-Cookie
      - Authorization
      url: http://localhost:8082
    todo-web-application:
      path: /**
      sensitive-headers:
      - Set-Cookie
      - Authorization
