logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoint:
    shutdown:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true